const apps=[
{name:'Core 1',ko:'코어 원',icon:'core1-icon.jpg',line:['One habit. One living promise.','습관 하나. 살아 있는 약속 하나.'],desc:['Choose one habit and let a tiny seed grow with every day you show up.','습관 하나를 고르고, 매일의 실천으로 작은 씨앗을 키워보세요.'],state:'live',href:'https://apps.apple.com/app/core-1/id6759274693'},
{name:'A Moment of Stillness',ko:'정적의 시간',icon:'stillness-icon.png',line:['Five quiet minutes to return to yourself.','나에게 돌아오는 조용한 5분.'],desc:['A minimal breathing timer with no voice, no music, and nothing to perform.','목소리도 음악도 성취도 없이, 숨의 리듬만 남기는 호흡 타이머.'],state:'live',href:'https://apps.apple.com/app/a-moment-of-stillness/id6759428219'},
{name:'Punch Cat',ko:'각성 한 방',icon:'punchcat-icon.png',line:['The screen-time wake-up call with claws.','발톱 있는 스크린 타임 모닝콜.'],desc:['A spirited cat interrupts endless scrolling and helps you put the phone down.','끝없는 스크롤을 도도한 고양이가 끊어주고 폰을 내려놓게 도와줘요.'],state:'soon'},
{name:'PawMic',ko:'포마이크',icon:'pawmic-icon.png',line:['Say it now. Remember it when it matters.','지금 말하고, 필요할 때 기억하세요.'],desc:['A voice-first pet diary for symptoms, vet visits, photos, and everyday moments.','증상, 병원 방문, 사진과 일상을 음성으로 남기는 반려동물 기록장.'],state:'review'},
{name:'The Sense of Moment',ko:'찰나의 감각',icon:'chalna-icon.jpg',line:['See a year of feelings in color.','일 년의 감정을 색으로 바라보세요.'],desc:['Choose the color that feels like now. Over time, the moments become a pattern.','지금 같은 색 하나를 고르면, 쌓인 순간들이 나만의 패턴이 됩니다.'],state:'review'},
{name:'One Line',ko:'한 줄',icon:'one-line.png',line:['A whole day, kept in one honest line.','하루를 솔직한 한 줄로.'],desc:['A deliberately small journal for the thought you do not want to lose.','놓치고 싶지 않은 생각 하나만 남기는 의도적으로 작은 기록장.'],state:'soon'},
{name:'MeetKeep',ko:'밋킵',icon:'meetkeep.png',line:['Remember the people behind the meeting.','미팅 너머의 사람을 기억하세요.'],desc:['Keep the useful context, promises, and next step after every conversation.','대화 뒤에 남는 맥락과 약속, 다음 단계를 간단히 보관하세요.'],state:'soon'},
{name:'5 Second Miracle',ko:'5초의 기적',icon:'5secondmiracle-icon.png',line:['A tiny pause can change the next moment.','짧은 멈춤이 다음 순간을 바꿉니다.'],desc:['A playful five-second reset for the moments when starting feels hardest.','시작이 가장 어려운 순간을 위한 장난스럽고 짧은 5초 리셋.'],state:'soon'}];
let lang='en';const labels={en:{live:'On the App Store',review:'In review',soon:'In the works',open:'View on App Store'},ko:{live:'App Store 출시',review:'심사 중',soon:'만드는 중',open:'App Store에서 보기'}};
function renderApps(){const k=lang==='en'?0:1,l=labels[lang];document.getElementById('appGrid').innerHTML=apps.map((a,i)=>{const x=`<article class="appCard"><div class="appTop"><img src="${a.icon}" alt="${a.name} app icon"><span class="status ${a.state}">${l[a.state]}</span></div><p class="number">0${i+1}</p><h3>${a.name}</h3><p class="koreanName">${a.ko}</p><p class="appLine">${a.line[k]}</p><p class="appDesc">${a.desc[k]}</p>${a.href?`<span class="cardLink">${l.open} ↗</span>`:''}</article>`;return a.href?`<a class="cardWrap" href="${a.href}" target="_blank" rel="noreferrer">${x}</a>`:`<div class="cardWrap">${x}</div>`}).join('')}
function setLang(v){lang=v;document.documentElement.lang=v;document.querySelectorAll('[data-en]').forEach(e=>e.textContent=e.dataset[v]);document.querySelectorAll('[data-set-lang]').forEach(b=>b.classList.toggle('active',b.dataset.setLang===v));localStorage.setItem('iamcraft-lang',v);renderApps()}
document.querySelectorAll('[data-set-lang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.setLang)));setLang(localStorage.getItem('iamcraft-lang')||(navigator.language.toLowerCase().startsWith('ko')?'ko':'en'));
